### ISSUE TITLE
autogit needs after every change in .conf `rm -r -f ~/autogit/packages` to work correctly.

### ISSUE THREAD

**Issue by D33M0N** [puxplaying/autogit#6]
autogit needs after every change in .conf `rm -r -f ~/autogit/packages` to work correctly.
If you don't, then it ignores changes you made to .conf and just does whatever you did previously with previous conf.
Changed branch in .conf? Nope, you didn't, unless you did also `rm -r -f ~/autogit/packages` afterwards. If you didn't, it still uses the previous PKGBUILD with old branch build.

**Comment by puxplaying** [comment]
Have you checked `autogit -h` as described in the README?
There is basically no way to work around a switching branch other than deleting the source git repo.

`autogit -b` is exactly what you would need in this case and what it is for!
