### ISSUE TITLE
please don't auto-delete previous packages after build.

### ISSUE THREAD

**Issue by D33M0N** [puxplaying/autogit#7]
How about leave some versions still in localrepo, not just the last version possible?
Or make it configurable.
Even worse was, when I first tried to build newer version. Then did build an older version for checking it out and in the end of creating package, it deleted it instantly... because version number lower?

**Comment by puxplaying** [comment]
You're right as `autogit` is configured to only keep the latest package version, since you normally don't do downgrades on packages, but fix the PKGBUILD instead. I try to implement a setting for those who wish to change that.
